[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AsyncIOThreadsCount=16
Session\DefaultSavePath=/data/torrents/
Session\DiskCacheSize=1024
Session\DiskCacheTTL=120
Session\FilePoolSize=500
Session\HashingThreadsCount=4
Session\IgnoreSlowTorrentsForQueueing=true
Session\MaxActiveDownloads=20
Session\MaxActiveTorrents=50
Session\MaxActiveUploads=20
Session\MaxConcurrentHTTPAnnounces=100
Session\MaxConnections=1500
Session\MaxConnectionsPerTorrent=500
Session\MaxUploads=100
Session\MaxUploadsPerTorrent=20
Session\Port=6881
Session\QueueingSystemEnabled=true
Session\SSL\Port=64145
Session\SendBufferLowWatermark=1024
Session\SendBufferWatermark=3072
Session\SendBufferWatermarkFactor=250
Session\SlowTorrentsDownloadRate=100
Session\SocketBacklogSize=100
Session\SocketReceiveBufferSize=4096
Session\SocketSendBufferSize=4096
Session\TempPath=/data/torrents/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\ResolvePeerCountries=false
Connection\UPnP=false
Downloads\SavePath=/data/torrents/
Downloads\TempPath=/data/torrents/incomplete/
WebUI\Address=0.0.0.0
WebUI\AuthSubnetWhitelist=0.0.0.0/0, ::/0
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\LocalHostAuth=false
WebUI\ServerDomains=*
